# Package configuration for DOOMLOADER

include(CMakePackageConfigHelpers)

# CPack configuration
set(CPACK_PACKAGE_NAME "DOOMLOADER")
set(CPACK_PACKAGE_VENDOR "DOOMLOADER Project")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Standalone Amp Simulator with Neural Modeling")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_INSTALL_DIRECTORY "DOOMLOADER")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")

# Platform-specific packaging
if(DOOMLOADER_WINDOWS)
    set(CPACK_GENERATOR "WIX;ZIP")
    set(CPACK_WIX_UPGRADE_GUID "12345678-1234-1234-1234-123456789012")
elseif(DOOMLOADER_APPLE)
    set(CPACK_GENERATOR "DragNDrop;TGZ")
    set(CPACK_DMG_VOLUME_NAME "DOOMLOADER")
    set(CPACK_DMG_FORMAT "UDZO")
elseif(DOOMLOADER_LINUX)
    set(CPACK_GENERATOR "DEB;RPM;TGZ")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "DOOMLOADER Project")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libasound2, libjack-jackd2-0")
    set(CPACK_RPM_PACKAGE_LICENSE "MIT")
    set(CPACK_RPM_PACKAGE_REQUIRES "alsa-lib, jack-audio-connection-kit")
endif()

# Component installation
set(CPACK_COMPONENTS_ALL 
    Runtime 
    Development 
    Documentation 
    Presets
    Examples
)

set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "DOOMLOADER Runtime")
set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "Core DOOMLOADER application and plugins")
set(CPACK_COMPONENT_RUNTIME_REQUIRED ON)

set(CPACK_COMPONENT_DEVELOPMENT_DISPLAY_NAME "Development Headers")
set(CPACK_COMPONENT_DEVELOPMENT_DESCRIPTION "Headers for DOOMLOADER development")
set(CPACK_COMPONENT_DEVELOPMENT_DEPENDS Runtime)

set(CPACK_COMPONENT_DOCUMENTATION_DISPLAY_NAME "Documentation")
set(CPACK_COMPONENT_DOCUMENTATION_DESCRIPTION "User and developer documentation")

set(CPACK_COMPONENT_PRESETS_DISPLAY_NAME "Default Presets")
set(CPACK_COMPONENT_PRESETS_DESCRIPTION "Default amp and effect presets")
set(CPACK_COMPONENT_PRESETS_DEPENDS Runtime)

set(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "Example Projects")
set(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "Example projects and templates")

include(CPack)